spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/daydayup_2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:统计，log4j:日志，wall:防火墙
    #如果允许时报错 java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入log4j依赖即可，maven地址：https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties:
      druid.stat.mergeSql: true
      druid.stat.slowSqlMillis: 1000

server:
  port: 8088
